sonar.projectKey=energy-app-source
sonar.organization=l01-mobileapp-helloworld

sonar.sources=app,components,hooks,constants

sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info