sonar.projectKey=energy-app-source
sonar.organization=nhom-helloworld-lop-l01

sonar.sources=src

sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info