name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - run: npm install --legacy-peer-deps

      - run: npm run test -- --coverage

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: coverage/lcov-report

      - run: npm install -g sonarqube-scanner

      - run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
